name: All OS
on: [push]

jobs:
  apple-clang:
    name: AppleClang XCode ${{ matrix.xcode }} MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [macos-13]
        xcode: [14.3, 15.2]
        include:
          - xcode: 13
            os: macos-12
            arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c8696863d371ab7f46e213d8f5ca923c4aef2a00'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  linux-clang:
    name: Clang ${{ matrix.clang }} Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-20.04]
        clang: [11, 12, 13, 14]
        include:
          - clang: 15
            os: ubuntu-22.04
            arch: x64
          - clang: 16
            os: ubuntu-22.04
            arch: x64
          - clang: 17
            os: ubuntu-22.04
            arch: x64
          - clang: 18
            os: ubuntu-22.04
            arch: x64

    steps:
      - uses: actions/checkout@v4

      # Minimum GCC version required for vcpkg
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c8696863d371ab7f46e213d8f5ca923c4aef2a00'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang }}
          platform: ${{ matrix.arch }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  linux-gcc:
    name: GCC ${{ matrix.gcc }} Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-22.04] 
        gcc: [11, 12, 13]

    steps:
      - uses: actions/checkout@v4

      # Minimum GCC version required for vcpkg
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c8696863d371ab7f46e213d8f5ca923c4aef2a00'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
          platform: ${{ matrix.arch }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  windows-msvc:
    runs-on: windows-latest
    name: MSVC ${{ matrix.msvc-version }} Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        arch: [x64]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          useVcpkgToolchainFile: true
          vcpkgGitCommitId: '01f602195983451bc83e72f4214af2cbc495aa94'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

